AWSTemplateFormatVersion: '2010-09-09'
Description: Simple monitoring lab

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /demo/app
      RetentionInDays: 7  